### ISSUE TITLE
Redundant Assignment and Potential Nil Pointer Dereference in `reconcileDesiredNetworkInterface`

### ISSUE THREAD

**Issue by sujeet01** [ironcore-dev/libvirt-provider#134]
In the `reconcileDesiredNetworkInterface` method, the line `mountedNic.networkInterface.Handle = providerNic.Handle` appears redundant as it is not utilized. This assumes `mountedNic` is non-nil before checking the map element, which may cause a panic.

**Comment by lukas016** [comment]
@sujeet01 could you pls provide link to problematic part of code? thx

**Comment by sujeet01** [comment]
> @sujeet01 could you pls provide link to problematic part of code? thx

https://github.com/ironcore-dev/libvirt-provider/blob/a4e506dffae7435e2ae9a65bcf2c0f72812dad44/pkg/controllers/machine_controller_nics.go#L219
