### ISSUE TITLE
qemu guest agent support

### ISSUE THREAD

**Issue by lukas016** [ironcore-dev/libvirt-provider#165]
# Summary

We need to implement support for [qemu guest agent](https://wiki.libvirt.org/Qemu_guest_agent.html)
This feature has to be optional and it can be enabled/disabled with argument.
We can inspire by virtlet implementation: https://github.com/onmetal/virtlet/blob/main/scheduler/scheduler.go#L124

## Basic example

If feature is enabled, we can add into specification path to socket QemuGuestAgentSocket (type string) or use type bool. I prefer use empty string for disable feature and path to socket for enable feature (it can be useful for ops guys).
I recommend use machine folder as default storage for socket.

## Motivation

We require this feature for manage/monitoring VM and getting additional information from VM.

**Comment by MalteJ** [comment]
Why do we need a qemu guest agent?
How are you going to extract the data and collect them?

**Comment by lukas016** [comment]
@MalteJ we require and we are using this feature actively. It is very useful for our ops guys during emergency situation. We don't use it for get any data from vm yet.
