### ISSUE TITLE
Simplify Setting Default Value for Flag `volume-size-resync-duration`

### ISSUE THREAD

**Issue by so-sahu** [ironcore-dev/libvirt-provider#199]
**Description**
In the current implementations, the default value for flag `volume-size-resync-duration` is set to zero value [here](https://github.com/ironcore-dev/libvirt-provider/blob/80ef3fbc7d797805eafbba7b43e755e8a1285184/provider/cmd/app/app.go#L107) and later on in the machine controller it's been set to 1 minute [here](https://github.com/ironcore-dev/libvirt-provider/blob/80ef3fbc7d797805eafbba7b43e755e8a1285184/pkg/controllers/machine_controller.go#L78). The default value can directly be set in the flag initialization which can simplify the flow and avoid unnecessary logic.

**Proposed Solution**
Update the flag initialization for `volume-size-resync-duration` in the libvirt-provider to directly set the default value to 1 minute. This will simplify the code and make it more straightforward.

**Additional context**
This change simplifies the code and makes it more consistent with the expected behavior.

**Comment by lukas016** [comment]
replace duration with interval and i am okay

**Comment by lukas016** [comment]
@so-sahu pls don't fix it in api.Machine PR, it is different topic which can be discuss long time so pls don't mix different topic in one PR, if it isn't necessary

**Comment by so-sahu** [comment]
Yes, I am not doing these changes in the api.Machine PR. I had given wrong issue reference in PR description it seems. I linked it with (https://github.com/ironcore-dev/libvirt-provider/issues/181) now.
