### ISSUE TITLE
Machine classes not linked to created machine pool during development deployment

### ISSUE THREAD

**Issue by so-sahu** [ironcore-dev/libvirt-provider#256]
**Description:**
During development deployment, the machine classes are not getting linked to the created machine pool. After conducting Root Cause Analysis, it was identified that in the [kustomization.yaml](https://github.com/ironcore-dev/libvirt-provider/blob/0b16082f331c888e6f4bf1826fb9b71b9c142f7f/config/development/kustomization.yaml#L4) file, a `namePrefix` is set to `libvirt-provider-dev-`. To resolve this issue, the names of machine classes in the [machineclasses.json](https://github.com/ironcore-dev/libvirt-provider/blob/main/config/development/machineclasses.json) file should be prefixed with `libvirt-provider-dev-`.

**To Reproduce**
- Apply the development kustomization config.
- List the machinePool and observe the linked machineClass.

**Expected behavior**
The machineClasses should get linked with the machinePool.

**Comment by lukasfrank** [comment]
The class including all properties needs to match. This is an expected behaviour.
