### ISSUE TITLE
Implement support for metrics server

### ISSUE THREAD

**Issue by lukas016** [ironcore-dev/libvirt-provider#57]
# Summary

We need for monitoring implement support of Prometheus metrics. The same functionality was before implemented directly in controller-runtime manager.

You can read more about implementation here: https://prometheus.io/docs/guides/go-application/
 We need implement only base support for metrics in this issue. Implementation of custom metrics will do in another issue.

Metrics server has to be optional and it can be enabled with arguments

## Motivation

Rise quality of service

**Comment by lukasfrank** [comment]
> @hardikdr @lukasfrank do you want to implement metrics server somewhere in shared library (example: IRI server) or every app will implement it own way?

@lukas016 I will approach you offline to discuss the details

**Comment by lukas016** [comment]
it was merged into osc/dev
