### ISSUE TITLE
Support for Resizing Attached Ceph Volumes

### ISSUE THREAD

**Issue by hardikdr** [ironcore-dev/libvirt-provider#58]
# Summary
This issue proposes a feature to enable resizing of already attached Ceph volumes in our system. The goal is to dynamically update the size of attached Ceph disks without manual intervention. 

Proposed Solution
The solution involves the development of a dedicated Go routine with the following functionalities:

1. Polling the Ceph Cluster: Continuously monitor the Ceph cluster to detect any changes in the size of the Ceph disks. This involves fetching the new size of the Ceph disk if it has been altered.  

2. Polling the VMs on the Host: Simultaneously, the routine should poll the virtual machines (VMs) running on the host to acquire the old-current size of the Ceph disk already attached to the VMs. The Go equivalent of the `virsh domblkinfo dom_uid vdb` command can be used.

3. Updating the Disk Size: When a discrepancy in size is detected, the routine should automatically update the size of the attached disk. This could be achieved with a command similar to `virsh blockresize dom_uid vdb 10G`.

## Motivation

Ensuring more flexibility and efficiency in disk management.

**Comment by lukas016** [comment]
main design look good. I have little problem with point 2. How do you mean polling virtual machine? What will be source of vm resources? I would like avoid polling from kubernetes api and i prefer use local cache which has to contain all resources of virtual machines and we can minimize load to API.

**Comment by hardikdr** [comment]
There could be 2 solutions to that, 
- `virsh domblkinfo dom_uid vdb` returns the size of the disk that's attached as vdb to the VM. 
- The second approach could be to store the currentSize of the disks to the `apiMachine` object in the store.  

So it is really not about polling but, cross-checking the size of the disks between the Ceph-cluster, and with the VM(either via virsh domblkinfo or store).

**Comment by lukas016** [comment]
i prefer solution compatible with `virsh domblkinfo dom_uid vdb`. We won't have dependency to API and we will be more flexible during implementation and implementing of live migration in future can be easier because we don't need synchronize information about volume size on multiple places (apiMachine and libvirt volume).
