### ISSUE TITLE
improve app logging

### ISSUE THREAD

**Issue by lukas016** [ironcore-dev/libvirt-provider#85]
# Summary

We need improve and standardize format of logs records because current implementation has few issues which can do problem with integration of log collector:

- "Main error" reason for terminate of application is printed with standard fmt.Println() when other errors use zap logger.
   https://github.com/ironcore-dev/libvirt-provider/blob/main/provider/cmd/main.go#L18
- Duplicated "main error" logs:
   ```text
   Error: failed to initialize machine class registry: unable to unmarshal machine classes: error converting YAML to JSON: yaml: line    2: did not find expected alphabetic or numeric character
   failed to initialize machine class registry: unable to unmarshal machine classes: error converting YAML to JSON: yaml: line 2: did     not find expected alphabetic or numeric character
   ```
- We should use production configuration as default. So i recommend disable development level for zap logger as default settings because if you need it, you can use argument --zap-devel
- Disable print of usage for every "main error" which terminated application. We can print usage, if users use wrong argument or required arguments are missing, but it doesn't make sense print usage for application runtime error.

## Motivation

Easier integration log collectors with our application

**Comment by lukas016** [comment]
@lukasfrank do you have any objections or advice before implementation? Replace of fmt.Println() will be little complicated, another points are small changes

**Comment by lukasfrank** [comment]
> @lukasfrank do you have any objections or advice before implementation? Replace of fmt.Println() will be little complicated, another points are small changes

In order to solve the main issue that the log-collector can't process an unformatted log , I would propose to init a `setup-logger` in the `main.go` like here: 
https://github.com/ironcore-dev/ironcore/blob/main/poollet/machinepoollet/cmd/machinepoollet/main.go

**Comment by lukas016** [comment]
> > @lukasfrank do you have any objections or advice before implementation? Replace of fmt.Println() will be little complicated, another points are small changes
> 
> In order to solve the main issue that the log-collector can't process an unformatted log , I would propose to init a `setup-logger` in the `main.go` like here: https://github.com/ironcore-dev/ironcore/blob/main/poollet/machinepoollet/cmd/machinepoollet/main.go

i tested you solution and really cannot work. Default controller-runtime logger is dummy logger which discard logs (no op) so it will hide errors, if you use wrong arguments or you don't use required arguments.

✘  10:15 ~/work/libvirt-provider [ 85-improve-app-logging-v2 | ✚ 1 …4 ] $ ./cmd -y
✘  10:15 ~/work/libvirt-provider [ 85-improve-app-logging-v2 | ✚ 1 …4 ] $
