### ISSUE TITLE
Provide tests for `ServeExec` 

### ISSUE THREAD

**Issue by lukasfrank** [ironcore-dev/libvirt-provider#90]
# Summary

A test for `ServeExec` should be provided to cover at least: 
- that a http request with a not expected method fails
- that a request with a not existing token fails
- that a token can't be used twice
- that a request with a valid token and a not existing machine fails

This should be implemented using `net/http/httptest`. 

_Originally posted by @lukasfrank in https://github.com/ironcore-dev/libvirt-provider/pull/65#discussion_r1432477420_

**Comment by lukas016** [comment]
@hardikdr i think, we use ginkgo and gomega for unit tests. Maybe you can check, if we can use something directly from gomega: https://onsi.github.io/gomega/#codeghttpcode-testing-http-clients and we don't have to combine many different libraries
